spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/modelo
    driver-class-name: org.postgresql.Driver
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
